sonar.projectKey=sonar-node-app
sonar.projectName=Sonar Node App
sonar.projectVersion=1.0

sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=squ_2017c85585af74990304d668fb77d523cff3da17
